Use docker_image instead of docker pull
mhutter/ansible-docker-systemd-service pull request #11
Opened 2019-02-16 00:30 UTC by varac

With a command 'docker pull' the resource always change.

2019-02-20 07:49 UTC, mhutter commented
Hmm, this has two drawbacks:
* `docker-py` is induced as an additional dependency (I found that it is usually missing on fresh systems) so we'd have to ensure it is installed before running `docker_image`

* `docker_image` will not update images that are already present on the system but might have changed on docker hub (eg. when using the `latest` tag). This can be enforced by setting `force` to true but this will in turn always mark the resource as changed IIRC... but then again, you should use versioned tags anway...

WDYT?

2019-02-20 10:05 UTC, varac commented
> docker-py is induced as an additional dependency (I found that it is usually missing on fresh systems) 
> so we'd have to ensure it is installed before running docker_image

Agreed, I found that having this drawback is worth having the advantage that the resource won't change on every run. I just wonder if we should document this dependency and offload it to the user how to install it, or create a package resource that would install it (but then, it might have a different name on different OSes...).

> 
> docker_image will not update images that are already present on the system but might have changed on docker hub (eg. when using the latest tag).
> This can be enforced by setting force to true but this will in turn always mark the resource as changed IIRC... but then again, you should use versioned tags anway...

No, using `force: True` only will only change the resource when an actual update happens. I just tried it to make sure, and pushed an update with `force: True`.

2019-02-22 10:05 UTC, mhutter requested changes
Can you also document the `docker-py` in the README please

2019-02-22 10:05 UTC, mhutter commented on tasks/install.yml
> +    force: True
Use `true`

2019-02-25 09:16 UTC, mhutter approved these changes

2019-02-25 09:16 UTC, merged