Fix container name used for systemd unit file etc.
mhutter/ansible-docker-systemd-service pull request #6
Opened 2018-09-29 14:15 UTC by jovandeginste

`name` seems to be the name of the role - my systemd unit files were
always called `mhutter.docker-systemd-service_container.service` which
was annoying and didn't scale...

This change requires you to use `container_name` to differentiate
containers.

2018-09-30 10:21 UTC, mhutter requested changes

2018-09-30 10:21 UTC, mhutter commented on defaults/main.yml
> +container_name: mycontainer
This should default to `{{ name }}` to have backwards compatibility. Otherwise, all existing deployments will break!

2018-09-30 10:22 UTC, mhutter commented
Hi @jovandeginste!
Hmm, what version of ansible are you using? Just yesterday I have successfully deployed 3 different containers using this roles, and all were correctly named.

2018-09-30 13:59 UTC, jovandeginste commented
@mhutter My ansible version:

```bash
$ ansible --version
ansible 2.5.1
```

2018-09-30 13:59 UTC, jovandeginste commented on defaults/main.yml
> +container_name: mycontainer
@mhutter agreed, wasn't sure if I should set this

2018-10-01 06:36 UTC, mhutter approved these changes

2018-10-01 06:37 UTC, merged

2018-10-01 06:37 UTC, mhutter commented
Thanks for your contribution!

2018-10-01 06:40 UTC, mhutter commented
Thanks for your contribution! 🤘

2018-10-01 07:36 UTC, jovandeginste commented
@mhutter Did you confirm the behaviour? Because I'm very new at ansible, so the problem could have been totally at my side ...

2018-10-01 12:00 UTC, mhutter commented
@jovandeginste No, but I wanted to do this change anyway